# Generated by Django 5.2.6 on 2025-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('opportunity', models.IntegerField()),
                ('candidate', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('race', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=200)),
                ('aggregate', models.IntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('disciplines', models.CharField(max_length=200)),
                ('num_candidates', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
