# Generated by Django 5.2.6 on 2025-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireScope', '0002_remove_candidateentry_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
