# Generated by Django 5.2.6 on 2025-09-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HireScope', '0003_candidateentry_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateentry',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='aggregate',
            new_name='Aggregate',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='disciplines',
            new_name='Disciplines',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='full_name',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='industry',
            new_name='Industry',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='institution',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='num_candidates',
            new_name='NumCandidates',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='opportunity',
            new_name='Opportunity',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='qualification',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='candidateentry',
            old_name='race',
            new_name='Race',
        ),
    ]
